### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by yangboz** [rafaelpsouza/haproxy-spring-boot#1]
After "vagrant up",
both of  web browering: "http://192.168.80.3/example/v1/items" throws:

503 Service Unavailable

No server is available to handle this request.

**Comment by rafaelpsouza** [comment]
Hi @yangboz. Thanks for reporting this issue.
I figured and fixed an issue with the health checks: https://github.com/rafaelpsouza/haproxy-spring-boot/commit/75d276fe6a7555d0553d5fd33e4cd19545617fe1

Please let me know if it is ok now. Thanks!
